name: Read Env Var and Print

on:
  workflow_dispatch:

jobs:
  print_env_var:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Print Environment Variable
        run: |
          echo "Environment Variable Value: ${{ vars.a }}"
